name = "pagecms"
main = "worker-static.mjs"
assets = { directory = "out/", binding = "ASSETS" }
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[placement]
mode = "smart"
